spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fam_sub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:file:.env[.properties]
users:
  excluded: ${USERS_EXCLUDED}
